[theme]
base = "light"
primaryColor = "#f3f907"
backgroundColor = "#0e0e35"
secondaryBackgroundColor = "#6d024b"
textColor = "#ffffff"
font = "sans-serif"

[server]
headless = true
enableCORS = false
port = 8501

[insert]
footer_css = '''
    <style>
        /* Your custom CSS styles */
        body {
            background-color: #0e0e35;
            color: #ffffff;
            font-family: Arial, sans-serif;
        }

        .streamlit-widget.stButton {
            background-color: #f3f907;
            color: #000000; /* Adjust text color for better visibility */
        }
    </style>
'''
